### PR TITLE
Keycloak role changes for RCIAM-793

### PR DESCRIPTION
**Pull request by laskasn**
Add client-scope configuration
In accordance to the ticket [RCIAM-793](https://jira.argo.grnet.gr/browse/RCIAM-793) 

Tested

### CODE REVIEW

**Comment by laskasn** [comment]
Including the mappers in the client scopes management. Converting to draft till it's completed and tested

**Comment by laskasn** [comment]
Added the client-scope mappers configuration tasks

**Comment by laskasn** [comment]
Added the client-scope {default, optional} configuration tasks

**Comment by laskasn** [comment]
It's now ready for review, let's resume it

**Comment by laskasn** [comment]
@NicolasLiampotis I also added the "clear previous setting" before adding the client-scope into the {default, optional} as suggested in our last call.
Also tested it (as always).
We can proceed with the review.

**Review by NicolasLiampotis — APPROVED** [review]
LGTM

**Pull request merged**
